controller_manager:
  ros__parameters:
    update_rate: 50 # Frecuencia de actualización del controlador (Hz)
    use_sim_time: true # Si se está utilizando tiempo simulado
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diffbot_base_controller:
      type: diff_bot_controller/DiffBotController

diffbot_base_controller:
  ros__parameters:
    left_wheel: "left_wheel_joint"
    right_wheel: "right_wheel_joint"
    publish_rate: 50
    cmd_vel_timeout: 0.5
    velocity_rolling_window_size: 10
